/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.DAO.UsuarioDAO;

import modelo.beans.Usuario;
import modelo.logic.UsuarioLogic;
/**
 *
 * @author Familia García Escob
 */
public class FrmLogin extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    static UsuarioDAO registro;

    /**
     * Creates new form login
     */
    public FrmLogin(UsuarioDAO registro) {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public boolean autenticacion(String correo, String contra){
        if (registro.buscar(correo) != -1) {
            Usuario temp = registro.usuarioPorIndex(registro.buscar(correo));
            if (temp.getContraseña()== contra) {
                this.setVisible(false);
            }
          //  mensajes.setText("Contraseña incorrecta");
        }else{
            //mensajes.setText("Correo no encontrado");
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borempl = new javax.swing.JPanel();
        BG = new javax.swing.JPanel();
        iniciose = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        bexit = new javax.swing.JPanel();
        xexit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chkContra = new javax.swing.JCheckBox();
        btnRegist = new javax.swing.JButton();
        bntInem = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        campoContraseña = new javax.swing.JPasswordField();

        borempl.setBackground(new java.awt.Color(102, 51, 0));
        borempl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        borempl.setForeground(new java.awt.Color(255, 255, 255));
        borempl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borempl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boremplMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boremplMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout boremplLayout = new javax.swing.GroupLayout(borempl);
        borempl.setLayout(boremplLayout);
        boremplLayout.setHorizontalGroup(
            boremplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        boremplLayout.setVerticalGroup(
            boremplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iniciose.setFont(new java.awt.Font("Roboto Black", 0, 26)); // NOI18N
        iniciose.setForeground(new java.awt.Color(0, 0, 0));
        iniciose.setText("Iniciar sesion");

        usuario.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        usuario.setText("Usuario");

        contraseña.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        contraseña.setText("Contraseña");

        bexit.setBackground(new java.awt.Color(255, 255, 255));
        bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bexitMouseEntered(evt);
            }
        });

        xexit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xexit.setText("X");

        javax.swing.GroupLayout bexitLayout = new javax.swing.GroupLayout(bexit);
        bexit.setLayout(bexitLayout);
        bexitLayout.setHorizontalGroup(
            bexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bexitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xexit, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
        );
        bexitLayout.setVerticalGroup(
            bexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bexitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xexit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        chkContra.setBackground(new java.awt.Color(255, 255, 255));
        chkContra.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        chkContra.setForeground(new java.awt.Color(0, 0, 0));
        chkContra.setText("mostrar contraseña");
        chkContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkContraActionPerformed(evt);
            }
        });

        btnRegist.setBackground(new java.awt.Color(255, 255, 255));
        btnRegist.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnRegist.setForeground(new java.awt.Color(0, 204, 204));
        btnRegist.setText("registrarse");
        btnRegist.setBorder(null);
        btnRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistActionPerformed(evt);
            }
        });

        bntInem.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        bntInem.setForeground(new java.awt.Color(255, 255, 255));
        bntInem.setText("Soy Empleado");
        bntInem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntInem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntInemMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntInemMouseEntered(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inicio de Sesion");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(153, 0, 153));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("J&J");

        campoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        campoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        campoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        campoContraseña.setForeground(new java.awt.Color(102, 102, 102));
        campoContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(BGLayout.createSequentialGroup()
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(iniciose))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(bntInem)
                        .addGap(51, 51, 51)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                .addGap(0, 267, Short.MAX_VALUE)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                        .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario)
                            .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseña)
                            .addComponent(chkContra))
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                        .addComponent(btnRegist, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338))))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iniciose)
                .addGap(30, 30, 30)
                .addComponent(usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkContra, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntInem)
                        .addGap(146, 146, 146))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)))
                .addComponent(jLabel1)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_bexitMouseClicked

    private void bexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bexitMouseEntered
        
    }//GEN-LAST:event_bexitMouseEntered

    private void boremplMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boremplMouseEntered
         borempl.setBackground(Color.white);
    }//GEN-LAST:event_boremplMouseEntered

    private void boremplMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boremplMouseExited
           borempl.setBackground(new Color(102,51,0));
    }//GEN-LAST:event_boremplMouseExited

    private void bntInemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntInemMouseEntered
                bntInem.setForeground(Color.black);
    }//GEN-LAST:event_bntInemMouseEntered

    private void bntInemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntInemMouseExited
                 bntInem.setForeground(Color.white);
    }//GEN-LAST:event_bntInemMouseExited

    private void chkContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkContraActionPerformed
         if(chkContra.isSelected()){
             campoContraseña.setEchoChar((char)0);
             
         }else{
             campoContraseña.setEchoChar('*');
         }
    }//GEN-LAST:event_chkContraActionPerformed

    private void btnRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistActionPerformed
           Registro frmRegistrarUsua=new Registro(this,true);
            frmRegistrarUsua.setVisible(true);
    }//GEN-LAST:event_btnRegistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         reservar frmPaginaPrinc=new reservar();  
           frmPaginaPrinc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin(registro).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel bexit;
    private javax.swing.JLabel bntInem;
    private javax.swing.JPanel borempl;
    private javax.swing.JButton btnRegist;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JCheckBox chkContra;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel iniciose;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel xexit;
    // End of variables declaration//GEN-END:variables
}
